
services:
  - type: web
    name: caipa-connect
    runtime: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - fromGroup: caipa-connect-env
      
envVarGroups:
  - name: caipa-connect-env
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
